"""Writes examples/assets/simple_hull.obj (+ .mtl): a small open boat for the examples.

A rounded hull (superellipse sections, pointed bow along -Z, flat transom at +Z),
an inner skin, the gunwale rim joining them, and two thwarts. Units are metres,
the gunwale at y = 0.35, the keel at y = -0.4 amidships. Regenerate with
    python tools/make_example_hull.py
"""
import math
import pathlib

LENGTH = 4.4
HALF_BEAM = 0.75
GUNWALE_Y = 0.35
KEEL_Y = -0.4
THICKNESS = 0.04
STATIONS = 24
SECTION_STEPS = 10
EXPONENT = 3.0  # superellipse: higher is boxier

OUT = pathlib.Path(__file__).resolve().parent.parent / "examples" / "assets"


def half_beam(t):
    """t: 0 at the transom, 1 at the bow."""
    taper = max(0.0, (t - 0.45) / 0.55)
    transom = 0.82 + 0.18 * min(t / 0.25, 1.0)
    return HALF_BEAM * transom * (1.0 - taper ** 1.8)


def keel_y(t):
    rise = max(0.0, (t - 0.6) / 0.4)
    return KEEL_Y + (GUNWALE_Y - 0.05 - KEEL_Y) * rise ** 2.2


def section(t, inset):
    """Points from the port gunwale over the keel to the starboard gunwale."""
    z = LENGTH * 0.5 - t * LENGTH
    beam = max(half_beam(t) - inset, 0.0)
    depth = max(GUNWALE_Y - keel_y(t) - inset, 0.0)
    points = []
    for i in range(-SECTION_STEPS, SECTION_STEPS + 1):
        phi = (i / SECTION_STEPS) * math.pi * 0.5  # -90 deg port gunwale .. 90 starboard
        c = math.sin(phi)
        s = math.cos(phi)
        x = beam * math.copysign(abs(c) ** (2.0 / EXPONENT), c)
        y = GUNWALE_Y - depth * abs(s) ** (2.0 / EXPONENT)
        points.append((x, y, z))
    return points


class Mesh:
    def __init__(self):
        self.vertices = []
        self.faces = {}  # material -> [(a, b, c)]

    def add(self, p):
        self.vertices.append(p)
        return len(self.vertices)

    def quad(self, material, a, b, c, d):
        self.faces.setdefault(material, []).extend([(a, b, c), (a, c, d)])

    def box(self, material, center, size):
        cx, cy, cz = center
        hx, hy, hz = size[0] * 0.5, size[1] * 0.5, size[2] * 0.5
        v = [self.add((cx + sx * hx, cy + sy * hy, cz + sz * hz)) for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)]
        # index: (sx, sy, sz) -> v[(sx>0)*4 + (sy>0)*2 + (sz>0)]
        for quad in [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]:
            self.quad(material, *[v[i] for i in quad])


def build():
    mesh = Mesh()
    outer = [[mesh.add(p) for p in section(j / STATIONS, 0.0)] for j in range(STATIONS + 1)]
    inner = [[mesh.add(p) for p in section(j / STATIONS, THICKNESS)] for j in range(STATIONS + 1)]
    n = len(outer[0])
    for j in range(STATIONS):
        for i in range(n - 1):
            mesh.quad("hull", outer[j][i], outer[j][i + 1], outer[j + 1][i + 1], outer[j + 1][i])
            mesh.quad("wood", inner[j][i], inner[j + 1][i], inner[j + 1][i + 1], inner[j][i + 1])
        # Gunwale rim, both sides.
        mesh.quad("trim", outer[j][0], outer[j + 1][0], inner[j + 1][0], inner[j][0])
        mesh.quad("trim", outer[j][n - 1], inner[j][n - 1], inner[j + 1][n - 1], outer[j + 1][n - 1])
    # Transom (j = 0): outer and inner skins closed by a plate, its top a rim.
    centre_outer = mesh.add((0.0, GUNWALE_Y, LENGTH * 0.5))
    for i in range(n - 1):
        mesh.faces.setdefault("hull", []).append((centre_outer, outer[0][i + 1], outer[0][i]))
    centre_inner = mesh.add((0.0, GUNWALE_Y, LENGTH * 0.5 - THICKNESS))
    for i in range(n - 1):
        mesh.faces.setdefault("wood", []).append((centre_inner, inner[0][i], inner[0][i + 1]))
    # Thwarts (seats).
    for z in (-0.6, 0.7):
        t = (LENGTH * 0.5 - z) / LENGTH
        mesh.box("trim", (0.0, GUNWALE_Y - 0.12, z), ((half_beam(t) - THICKNESS) * 2.0, 0.04, 0.28))
    return mesh


def smooth_normals(mesh):
    normals = [[0.0, 0.0, 0.0] for _ in mesh.vertices]
    for faces in mesh.faces.values():
        for a, b, c in faces:
            pa, pb, pc = (mesh.vertices[k - 1] for k in (a, b, c))
            u = [pb[i] - pa[i] for i in range(3)]
            v = [pc[i] - pa[i] for i in range(3)]
            nx, ny, nz = u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0]
            for k in (a, b, c):
                normals[k - 1][0] += nx
                normals[k - 1][1] += ny
                normals[k - 1][2] += nz
    result = []
    for x, y, z in normals:
        length = math.sqrt(x * x + y * y + z * z) or 1.0
        # Faces are written reversed (see main()), so the normals point the other way.
        result.append((-x / length, -y / length, -z / length))
    return result


def main():
    mesh = build()
    normals = smooth_normals(mesh)
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by tools/make_example_hull.py", "mtllib simple_hull.mtl", "o SimpleHull"]
    lines += ["v %.5f %.5f %.5f" % p for p in mesh.vertices]
    lines += ["vn %.5f %.5f %.5f" % n for n in normals]
    for material, faces in mesh.faces.items():
        lines.append("usemtl " + material)
        # Godot's front faces wind clockwise: write each triangle reversed.
        lines += ["f %d//%d %d//%d %d//%d" % (a, a, c, c, b, b) for a, b, c in faces]
    (OUT / "simple_hull.obj").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (OUT / "simple_hull.mtl").write_text(
        "# Generated by tools/make_example_hull.py\n"
        "newmtl hull\nKd 0.55 0.12 0.08\n\n"
        "newmtl wood\nKd 0.62 0.45 0.28\n\n"
        "newmtl trim\nKd 0.85 0.8 0.7\n",
        encoding="utf-8",
    )
    print("wrote", OUT / "simple_hull.obj", len(mesh.vertices), "vertices")


if __name__ == "__main__":
    main()
